### ISSUE TITLE
consensus: check for busy-loops in the reactor's `gossipDataRoutine` routine

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#2823]
Follow-up of  #2663.

The `gossipDataRoutine` is an infinite loop that attempts to send `BlockPart` messages and `Proposal` messages to a peer. There is one instance of this routine per connected peer.

This issue consider the logic for sending `BlockPart` messages to a peer. The original logic, refactored by #2663, has two scenarios:

1. The peer is looking for the same block that we are building or have built. If so, randomly pick a `Part` that we have and we assume the peer does not to have. If there is some, send the `Part` to the peer and update its state with the information that the peer now has that block `Part`.
2. The peer is behind in the consensus protocol, namely in a previous height. In this case, load the block that has been committed on that previous height, then randomly pick a `Part` that we assume the peer does not to have. If there is some, send the `Part` to the peer and update its state with the information that the peer now has that block `Part`.

In both scenarios, if we have a `Part` to send to the peer, we attempt sending it using the `peer.Send()` method, which is a blocking method. This method attempts to add the message the `sendQueue` of that channel. If there is space on that channel (the length of which is defined by the `SendQueueCapacity` flag), the method immediately returns true. Otherwise, it blocks until either some space in the send queue is freed, or when a timeout expires. In the latter case, and only in this case, it returns false.

The issue is that in the above enumerated scenarios the behavior when the `Send()` method fails is distinct:

1. If we fail sending the `Part` in this scenario, we restart the outer loop (`continue OUTER_LOOP`). This probably means that we are evaluating again the same or similar conditions, thus we are attempting again to send the same or another `Part` to the peer. This is a busy-waiting approach.
2. If we fail sending the `Part` in this scenario, we sleep for `config.PeerGossipSleepDuration` before restarting the the outer loop (`continue OUTER_LOOP`). The rationale is that after sleeping for a while, the local and remote state are updated and we are able to evaluate again the same conditions. This is not a busy-waiting approach.

We should understand which of the approaches is the right one and align their implementations. Moreover, we should avoid the busy-waiting/loop approach, since it consumes a lot of CPU resources while not necessarily being more efficient.

### Definition of Done

- [ ] Check which approach is the most appropriate
- [ ] Align the implementation to have the same approach in both cases
- [ ] Make sure that the selected approach does not produce a busy-loop behavior

**Comment by cason** [comment]
The decision here now depends on the output of https://github.com/cometbft/cometbft/issues/3186.

If we decide to go for `TrySend()`, we should sleep in case of unsuccessful calls, which will mean a full sending queue. We should try again after a short sleep, as now the sending queue can be available.

A corner case for when `Send()` fails is now covered by #3510. We shouldn't send to a channel that the peer does not implement/support, otherwise the method always returns `false`. In this case, not sleeping in case of failure produces a busy-waiting situation. Notice, however, that this only happens when the peer is a non-standard/upstream or tricked peer, that decides not implementing some channels (why would it?).
